owner: HyenaMC
repo: upptime

sites:
  - name: Skin Station
    url: https://account.teamhyena.org
  - name: Official Website
    url: https://minecraft.teamhyena.org
  - name: Gateway (NA)
    check: "tcp-ping"
    url: mc-na.teamhyena.org
    port: 25577
  - name: Gateway (CS)
    check: "tcp-ping"
    url: mc-cs.teamhyena.org
    port: 25577
  - name: Gateway (LA)
    check: "tcp-ping"
    url: mc-la.teamhyena.org
    port: 25577
  - name: Gateway (SF)
    check: "tcp-ping"
    url: mc-sf.teamhyena.org
    port: 25577
  - name: Gateway (TS)
    url: mc-ts.teamhyena.org
  - name: Gateway (NP)
    url: mc-np.teamhyena.org

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  cname: https://status.teamhyena.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: ocean
  name: HyenaMC Status Page
  introTitle: "**HyenaMC Status Page**"
  introMessage: This page monitors services and gateways offered by HyenaMC in real time, powered by Upptime and Github Actions. If you have trouble loading the content below, visit the Repo for raw data instead.
  navbar:
    - title: Github Repo
      href: https://github.com/$OWNER/$REPO
    - title: Skin Station
      href: https://account.teamhyena.org
    - title: Official Website
      href: https://minecraft.teamhyena.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
